(define pi 3.141592653589793)

(define (round-to n digits)
  (let ((factor (expt 10 digits)))
    (/ (round (* n factor)) factor)
  )
)

(define (FormatNumber num width precision)
  (let ((formatted (number->string (round-to num precision))))
    (string-append (make-string (max 0 (- width (string-length formatted))) #\space) formatted))
)

(define (PrintLine)
    (display "+----------+------------+------------+------------+")
    (newline)
)

(define (TrigTable start end step precision)
  (define (PrintRow deg)
    (display "| ")
    (display (FormatNumber deg 8 2))
    (display " | ")
    (let ((sin-value (sin (* (/ pi 180) deg)))
          (cos-value (cos (* (/ pi 180) deg)))
          (tan-value (tan (* (/ pi 180) deg))))
      (display (FormatNumber sin-value 10 precision))
      (display " | ")
      (display (FormatNumber cos-value 10 precision))
      (display " | ")
      (if (= (round-to cos-value precision) 0)
          (display "    inf   ")
          (display (FormatNumber tan-value 10 precision)))
      (display " |"))
    (newline)
  )

  (PrintLine)
  (display "| Degrees  |   sin(x)   |   cos(x)   |   tan(x)   |")
  (newline)
  (PrintLine)

  (let loop ((deg start))
    (when (<= deg end)
      (PrintRow deg)
      (loop (+ deg step))
    )
  )

  (PrintLine)
)
;; Пример вызова функции для вывода таблицы с шагом 5 градусов от 0 до 90 с точностью до 4 знаков после запятой
(TrigTable 0 90 5 4)