(define pi 3.141592653589793)

(define (round-to n digits)
  (let ((factor (expt 10 digits)))
    (/ (round (* n factor)) factor)))

(define (PrintRow deg precision)
  (display "| ")
  (display (round-to deg 2))
  (display " | ")
  (let ((sin-value (sin (* (/ pi 180) deg)))
        (cos-value (cos (* (/ pi 180) deg)))
        (tan-value (tan (* (/ pi 180) deg))))
    (display (round-to sin-value precision))
    (display " | ")
    (display (round-to cos-value precision))
    (display " | ")
    (if (= (round-to cos-value precision) 0)
        (display " inf ")
        (display (round-to tan-value precision)))
    (display " |"))
  (newline))

(define (TrigTable start end step precision)
  (display "-------------------------------------")
  (newline)
  (display "| Degrees | sin(x) | cos(x) | tan(x) |")
  (newline)
  (display "-------------------------------------")
  (newline)

  (let loop ((deg start))
    (when (<= deg end)
      (PrintRow deg precision)
      (loop (+ deg step))))

  (display "-------------------------------------"))

;; от 0 до 90  с шагом 5  с точностью до 4 знаков после запятой
(TrigTable 0 90 5 4)
